In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3, 4)
b = np.arange(12).reshape(4, 3)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
a@b

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [21]:
def reshape_matmul(a: np.ndarray, b: np.ndarray):
	# for each b column, separate out with an a matrix
	# i represents each column of output too
	output = np.zeros((a.shape[0], b.shape[1]))
	for i in range(b.shape[1]):
		a_matrix = a
		b_vector = b[:, i]
		for j in range(a.shape[1]):
			b_scalar = b_vector[j]
			a_vector = a_matrix[:, j]
			output[:, i] += b_scalar*a_vector
	return output
reshape_matmul(a, b)

array([[ 42.,  48.,  54.],
       [114., 136., 158.],
       [186., 224., 262.]])

In [ ]:
_